#Requires -Version 5.1
# Copies templates/host-always-on.body.md into repo-local IDE rule paths.
# Run from repo root:  powershell -NoProfile -ExecutionPolicy Bypass -File .\scripts\sync-host-integrations.ps1
Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

$RepoRoot = Split-Path -Parent $PSScriptRoot
$src = Join-Path $RepoRoot 'templates\host-always-on.body.md'
if (-not (Test-Path -LiteralPath $src)) {
  Write-Error "Missing $src"
  exit 1
}

# Must specify UTF-8: default system encoding mis-decodes em dash, middle dot, arrows in the template.
$body = Get-Content -LiteralPath $src -Raw -Encoding utf8
$banner = "<!-- Generated by scripts/sync-host-integrations.ps1 - edit templates/host-always-on.body.md -->`n`n"

$cursorDir = Join-Path $RepoRoot '.cursor\rules'
$windsurfDir = Join-Path $RepoRoot '.windsurf\rules'
$clineDir = Join-Path $RepoRoot '.clinerules'
$ghDir = Join-Path $RepoRoot '.github'

foreach ($d in @($cursorDir, $windsurfDir, $clineDir, $ghDir)) {
  if (-not (Test-Path -LiteralPath $d)) {
    New-Item -ItemType Directory -Path $d -Force | Out-Null
  }
}

# Cursor .mdc: YAML front matter + body (ASCII in YAML for parser safety)
$cursorFront = "---`r`ndescription: SIGNAL workspace defaults (tiers, templates, workflows)`r`nalwaysApply: true`r`n---`r`n`r`n"

$cursorPath = Join-Path $cursorDir 'signal.mdc'
Set-Content -LiteralPath $cursorPath -Value ($cursorFront + $body.TrimEnd() + "`n") -Encoding utf8

$plainMd = $banner + $body.TrimEnd() + "`n"
Set-Content -LiteralPath (Join-Path $windsurfDir 'signal.md') -Value $plainMd -Encoding utf8
Set-Content -LiteralPath (Join-Path $clineDir 'signal.md') -Value $plainMd -Encoding utf8
Set-Content -LiteralPath (Join-Path $ghDir 'copilot-instructions.md') -Value $plainMd -Encoding utf8

Write-Host 'sync-host-integrations: OK' -ForegroundColor Green
Write-Host "  -> $cursorPath"
Write-Host "  -> $(Join-Path $windsurfDir 'signal.md')"
Write-Host "  -> $(Join-Path $clineDir 'signal.md')"
Write-Host "  -> $(Join-Path $ghDir 'copilot-instructions.md')"
exit 0
